### ISSUE TITLE
Imprecise Results using getAllAliases()

### ISSUE THREAD

**Issue by ufarooq** [CROSSINGTUD/SPDS#65] opened 2019-04-30 23:25 UTC
I am using almost same classes as BoomerangExampleTarget example provides, except fields are non-static. When I query results I get imprecise results. These results don't even match to Class hierarchy. When I query on last line, results include ``l0[a, b, nested, field]`` and `` $stack4[b, nested, field]``  that doesn't make sense at all. 

```java 
a = new ClassWithField();
a.field = new ObjectOfInterest();
b = (ClassWithField)identity(a);
n = new NestedClassWithField();
n.nested = b;
n.nested.field.poi = x*y; // query here for  n.nested.field
```

**Comment by johspaeth** [comment] 2019-05-01 12:45
That is the reason why the method [getAllAliases](https://github.com/CROSSINGTUD/WPDS/blob/dbd9a48e0b69d88524890ba742e35e118ea309df/boomerangPDS/src/main/java/boomerang/results/BackwardBoomerangResults.java#L130) is deprecated. It does not properly extract the fields. As we have not been using this method actively so far, we haven't fixed it.

**Comment by ufarooq** [comment] 2019-05-01 16:36
Thanks @johspaeth for quick reply. In that case, What is a good alternative? Also, you might want to fix the [Example](https://github.com/CROSSINGTUD/WPDS/blob/master/boomerangPDS/src/main/java/boomerang/example/ExampleMain.java) so people don't use this API.

**Comment by zepalmer** [comment] 2019-07-26 20:45
We've just run into this issue as well.  As mentioned above, the `getAllAliases` method is used in the [example file](https://github.com/CROSSINGTUD/WPDS/blob/08af150be60a9d3e2a79f4a283af407aa47aab21/boomerangPDS/src/main/java/boomerang/example/ExampleMain.java#L138) which is linked from the [repo documentation](https://github.com/CROSSINGTUD/WPDS/blob/master/README.md).  The Boomerang [unit tests](https://github.com/CROSSINGTUD/WPDS/blob/08af150be60a9d3e2a79f4a283af407aa47aab21/boomerangPDS/src/test/java/test/core/AbstractBoomerangTest.java#L378) also appear to make use of this method; should we avoid using that testing framework as well?

Is there another method we should be calling on the analysis result to find out which variables alias the one we want to know about?  Any advice on how to use the artifact would be appreciated!

**Comment by johspaeth** [comment] 2019-08-10 18:30
@zepalmer Thanks a lot for reporting. 

I still want to fix the method, it is an implementation issues that needs some refactoring but it is not conceptually. I hope to get it done soon (and hence did not delete occurrences of the method). However, the results the method returns are definitely incorrect. As @ufarooq pointed out the `getAllAliases` method still builds access path that do not even match in the class hierarchy.  

You can use the testing framework except the tests that rely on the `getAllAliases` method. Unfortunately, there is no alternative to the `getAllAliases` method.

**Comment by johspaeth** [comment] 2020-07-11 06:33
I am working on [version 3 of Boomerang](https://github.com/CodeShield-Security/SPDS) which will be merged to this repo from time to time. In version 3 the issue is solved.

**Closed by johspaeth** 2020-07-11 06:33 UTC
